Merge code "Stałe i annotacje"
Timek12/pio_git_rhymers pull request #2
Opened 2024-05-06 09:33 UTC by KacperJarosik

Task:
• Sklonuj repozytorium do którego zostałeś dodany i utwórz nowy branch
poleceniem (polecenie git checkout -b constants)
6. Przejrzyj kod w poszukiwaniu literałów (napisy, liczby), które można by zastąpić
deklaracjami stałych (np. w klasie DefaultCountingOutRhymer liczby -1 i 12).
Wygeneruj odpowiednie stałe używając opcji Refactor → Extract Constant.
7. Ustaw modyfikator final przy niemutowalnych (nie zmieniających wartości)
atrybutach klas.
8. Użyj annotacji @OverRide przy metodach tam gdzie jest to możliwe.
• Prześlij zmiany do zdalnego repozytorium (właściciela) – polecenie git push
origin constants.
• Przejdź na główną stronę repozytorium i wybierz opcję New pull request.
• Jako base repository wybierz repozytorium właściciela i branch master, a jako
head repository wybierz branch na którym pracowałeś, po czym kliknij Create
pull request.
• Przejdź do strony z nowo utworzonym pull requestem i z kliknij zębatkę przy
liście Reviewers, wybierz właściciela repozytorium jako recenzenta kodu
(reviewer).
• Na tej samej stronie powiąż pull request z Issue (opcja Development panelu
bocznego po prawej stronie).

2024-05-06 13:42 UTC, Timek12 requested changes
- Constants should be named uppercase
- Add final keyword to variables where possible

2024-05-07 08:09 UTC, KacperJarosik commented
there is a new version of the code

2024-05-07 14:27 UTC, Timek12 requested changes
OK, but add final keyword to ret variable in FifoRhymer.java and IntLinkedList.java

2024-05-07 17:58 UTC, KacperJarosik commented
done

2024-05-08 17:34 UTC, Timek12 approved these changes
Great

2024-05-19 12:28 UTC, merged